### PR TITLE
Jeongmin/home feed list

### PR DESCRIPTION
**Pull request by JeongMinCha**
1. RecyclerView added in home feed activity
2. Adapter dealing with the list of the card items in home feed.
3. When the card item is clicked, the club feed activity will appear.

### CODE REVIEW

**Comment by JeongMinCha** [comment]
@kyeongwan check it asap

**Comment by kyeongwan** [comment]
Why don`t you use Korean?

**Comment by JeongMinCha** [comment]
@kyeongwan I love English 👍 You can use a language you love.

**Comment by kyeongwan** [comment]
See you later, OPPA

**Comment by JeongMinCha** [comment]
@kyeongwan Anyway, please check it asap or give me your convenient time.

**Comment by kyeongwan** [comment]
OK, I will.

**Pull request merged**
